apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink-pdd:v1.4.2
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        resources:
          requests:
            memory: "512Mi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: JOB_MANAGER_HEAP_MB
          value: "2048"
        - name: STATE_CHECKPOINTS_DIR
          value: "hdfs://abc"